Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  nodes = [
    {name: "node1", ip: "192.168.56.11"},
    {name: "node2", ip: "192.168.56.12"},
    {name: "node3", ip: "192.168.56.13"},
  ]

  nodes.each do |n|
    config.vm.define n[:name] do |node|
      node.vm.hostname = n[:name]
      node.vm.network "private_network", ip: n[:ip]

      node.vm.provider "virtualbox" do |vb|
        vb.memory = 2048
        vb.cpus = 2
      end
    end
  end
end