# Generated by Django 6.0 on 2026-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='platform',
            field=models.CharField(blank=True, default='MANUAL', max_length=30),
        ),
        migrations.AddField(
            model_name='task',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='provider_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
