# Generated by Django 6.0 on 2026-02-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_platform_task_poster_url_task_provider_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('platform', 'provider_id'), name='uniq_platform_provider'),
        ),
    ]
